# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('version', models.IntegerField(default=1)),
                ('content_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('tags', models.TextField(max_length=10000)),
                ('linked', models.BooleanField(default=False)),
                ('creator', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('expert_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_one_pk', models.IntegerField()),
                ('content_two_pk', models.IntegerField()),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('link_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('lat1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('long1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lat2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('long2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpediav2.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_of_expertise', models.TextField(max_length=10000)),
                ('research_institution', models.TextField(default='INDEPENDENT', max_length=200)),
                ('specific_achievements', models.TextField(max_length=10000)),
                ('tags', models.TextField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpediav2.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('auto_uname', models.CharField(max_length=15, unique=True)),
                ('auto_pword', models.TextField(max_length=15)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpediav2.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
